### ISSUE TITLE
Accents?

### ISSUE THREAD

**Issue by hrdlnk** [liffiton/code2tex#5]
I’ve got some utf8 characters in my files such as **`Ë`** which fail to print in the pdf.

**`ORIËNTATIE`** turns into **`ORI NTATIE`**

**Comment by hrdlnk** [comment]
I found a solution [here](https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings). It adds a table covering most special characters in latin languages so listings can interpret them. Not ideal but fits my needs for now.

**Comment by liffiton** [comment]
Another solution is to use `xelatex` in place of `pdflatex` for better unicode support and to use LaTeX package `lmodern` to provide a good font with the proper glyphs.  That appears to cover Latin characters anyway.  I haven't found a way to handle non-Latin characters within the file listing.

I'll add a conditional package import to the template that will use `lmodern` if it is available and add a note about `xelatex` to the README.
