### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by ceciliassis** [liffiton/code2tex#6]
The line 103 gives a syntax error when trying to run the file.
![](https://cloud.githubusercontent.com/assets/9968803/25186575/ebbe8fa8-24f6-11e7-813a-18b5e50e1ded.png)

**Comment by liffiton** [comment]
Yeah; somehow I converted the scripts to run on Python 3 at some point without changing the #! line at the start to match.  I'll make them all use Python 3 as their interpreter and update the README to match.  Thanks for reporting that!
