### ISSUE TITLE
Showing invisible characters

### ISSUE THREAD

**Issue by wenting-zhao** [liffiton/code2tex#8]
Just thought it'd be nice to have an optional feature which shows invisible characters (for example, tabs, spaces, etc.), so that we don't need to open a text editor to check the consistence of indentation or whatever.  This would be particularly useful for the languages that use indentation to indicate the blocks of code.

**Comment by liffiton** [comment]
It's in there now, controlled by the "-s" command line option.  The way the TeX package prints whitespace is a bit ugly, but the characters should be easily visible at least.

**Comment by liffiton** [comment]
(Also, I wouldn't bother checking the consistency of the whitespace as long as it looks okay and as long as the code runs correctly.  If someone somehow managed to mix tabs and spaces in such a way that it looks fine and is consistent as far as Python is concerned, then it's not worth the effort to try to track that down manually.)
