### ISSUE TITLE
option to select code highlighting

### ISSUE THREAD

**Issue by TejasAvinashShetty** [liffiton/code2tex#9]
Dear @liffiton @alanrussian ,
First of all, **thank you** for making this wonderful repository.
Before stumbling on to this repository, I had to upload the code files to a Github private repository and then print the webpage as a pdf.

Is there any way to add an option to select a different code highlighting?

**Comment by liffiton** [comment]
You're welcome!  I'm glad you've found it helpful.

Can you give a bit more detail?  I'm not quite sure what you mean.  Are you talking about selecting a different color theme?  Or selecting a language syntax manually instead of automatically?

**Comment by TejasAvinashShetty** [comment]
Different colour theme

**Comment by liffiton** [comment]
I see.  There are no themes provided in the Latex package this uses, so colors are set manually in the code [here](https://github.com/liffiton/code2tex/blob/b78997af7391b8c8b64beb1c34418aae4e876ea4/code2tex.py#L96-L99).  You can edit those colors either in the program itself before you generate the Latex files with it or in a Latex file before you generate a PDF from it.

**Comment by TejasAvinashShetty** [comment]
Thank you

**Comment by TejasAvinashShetty** [comment]
closing issue
